# Generated by Django 4.0.5 on 2022-06-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Medidasteste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('Ptronco', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Pcintura', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Pabdomen', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Pquadril', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PantebracoD', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PbracoD', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PcoxaD', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PpernaD', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Ir_vir', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Dinamometro', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Sentar_levantar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Marcha', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testes.namelist')),
            ],
        ),
    ]
